- name: Install X11 packages
  become: yes
  xbps:
    package:
      - disputils
      - hsetroot
      - scrot
      - wmctrl
      - wmutils-core
      - wmutils-opt
      - xcalib
      - xclip
      - xdo
      - xdotool
      - xev
      - xf86-input-libinput
      - xinit
      - xinput
      - xkill
      - xorg-minimal
      - xorg-server
      - xorg-video-drivers
      - xoris
      - xprop
      - xrandr
      - xrdb
      - xsel
      - xset
      - xsetroot
      - xtitle
      - xwininfo
    state: present

- name: Install fonts
  become: yes
  xbps:
    package: dejavu-fonts-ttf
    state: present

- name: Install Hiragana, Katakana, Kanji fonts
  become: yes
  xbps:
    package:
      - font-hanazono
      - ipafont-fonts-otf
    state: present

- name: Synchronize X11 files
  vars:
    dir: x11
  include_role:
    name: lib
    tasks_from: synchronize-files
