- name: Install audio system
  include_tasks: install-audio-system.yaml

- name: Install X11
  include_tasks: install-x11.yaml

- name: Install Signal Private Messenger
  become: yes
  xbps:
    package:
      - Signal-Desktop
    state: present
