- name: Install audio system
  import_tasks: install-audio-system.yaml

- name: Install X11
  import_tasks: install-x11.yaml

- name: Install Signal Private Messenger
  become: yes
  xbps:
    package:
      - Signal-Desktop
    state: present

- name: Install tool to open files based on MIME type
  become: yes
  xbps:
    package:
      - run-mailcap
    state: present
