export CPATH=":{HOME}/.local/include:${CPATH}"
export INFOPATH="${HOME}/.local/share/info:${INFOPATH}"
export LD_LIBRARY_PATH="${HOME}/.local/lib:${LD_LIBRARY_PATH}"
export LIBRARY_PATH="${HOME}/.local/lib:${LIBRARY_PATH}"
export PATH="${HOME}/bin:${HOME}/.local/bin:${PATH}"
