- name: Install documentation tools
  import_tasks: install-documentation-tools.yaml

- name: Provision mail environment
  import_tasks: provision-mail-environment.yaml

- name: Provision base development environment
  import_tasks: provision-base-development-environment.yaml

- name: Provision Python development environment
  import_tasks: provision-python-development-environment.yaml

- name: Provision Emacs
  import_tasks: provision-emacs.yaml

- name: Make directory for user notes
  become: yes
  file:
    group: '{{ user }}'
    mode: 0755
    owner: '{{ user }}'
    path: '/home/{{ user | mandatory }}/notes/'
    state: directory

- name: git clone my notes
  git:
    dest: '/home/{{ user | mandatory }}/notes/public'
    repo: 'https://github.com/Negdayen/notes.git'
