- name: Install emacs package
  xbps:
    package:
      - emacs-x11

- name: Install other text editing packages
  xbps:
    package:
      - dict
      - yank

- name: git clone emacs.d
  git:
    dest: '/home/{{ user | mandatory }}/.emacs.d'
    repo: 'https://github.com/Negdayen/.emacs.d.git'

- name: Fix .emacs.d permissions and user owner
  shell: |
    find '/home/{{ user | mandatory }}/.emacs.d/' | xargs -I@ chown {{ user | mandatory }}:{{ user | mandatory }} @
    find '/home/{{ user | mandatory }}/.emacs.d/' -type d | xargs -I@ chmod 755 @
    find '/home/{{ user | mandatory }}/.emacs.d/' -type f | xargs -I@ chmod 644 @
