- name: Install necessary packages for emacs
  become: yes
  xbps:
    package:
      - emacs-x11
      - gnupg2

- name: Install other text editing packages
  become: yes
  xbps:
    package:
      - aspell
      - aspell-en
      - dict
      - yank

- name: git clone emacs.d
  git:
    dest: '/home/{{ user | mandatory }}/.emacs.d'
    repo: 'https://github.com/Negdayen/.emacs.d.git'
