- name: Provision Google Cloud SDK
  import_tasks: provision-google-cloud-sdk.yaml

- name: Provision K3s
  import_tasks: provision-k3s.yaml

- name: Provision libvirt
  import_tasks: provision-libvirt.yaml

- name: Provision RDP client
  import_tasks: provision-rdp-client.yaml

- name: Provision QEMU
  import_tasks: provision-qemu.yaml
