- name: Install K3s container packages
  become: yes
  xbps:
    package:
      - buildah
      - kubernetes-helm
      - podman
    state: present

- name: Download K3s
  become: yes
  get_url:
    checksum: sha256:c257e119158feee992dc4397be00490103f0dde5af4b014e8d0f17f9db35ef00
    dest: '/bin/k3s'
    group: root
    mode: '0755'
    owner: root
    url: 'https://github.com/k3s-io/k3s/releases/download/v1.21.3%2Bk3s1/k3s'

- name: Synchronize K3s files
  vars:
    dir: k3s
  include_role:
    name: lib
    tasks_from: synchronize-files

- name: Create service supervision links
  become: yes
  loop:
    - path: /etc/sv/k3s-server/supervise
      src: /run/runit/supervise.k3s-server/
    - path: /etc/sv/k3s-server/log/supervise
      src: /run/runit/supervise.k3s-server-log/
    - path: /etc/sv/k3s-agent/supervise
      src: /run/runit/supervise.k3s-agent/
    - path: /etc/sv/k3s-agent/log/supervise
      src: /run/runit/supervise.k3s-agent-log/
    - path: /var/service/k3s-server
      src: /etc/sv/k3s-server/
  file:
    follow: no
    force: yes
    group: root
    mode: 0755
    owner: root
    path: '{{ item.path }}'
    src: '{{ item.src }}'
    state: link

- name: Start k3s-server
  become: yes
  runit:
    name: k3s-server
    state: started

- name: Create root kubectl configuration directory
  become: yes
  file:
    group: root
    mode: 0755
    owner: root
    path: /root/.kube
    state: directory

- name: Wait for K3s to populate /etc/rancher
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml

- name: Install root kubectl config
  become: yes
  command: |
    install -o root -g root -m '0600' '/etc/rancher/k3s/k3s.yaml' '/root/.kube/config'

- name: Create user kubectl configuration directory
  file:
    group: '{{ user | mandatory }}'
    mode: 0755
    owner: '{{ user | mandatory }}'
    path: '/home/{{ user | mandatory }}/.kube'
    state: directory

- name: Install user kubectl config
  become: yes
  command: |
    install -o '{{ user | mandatory }}' \
            -g '{{ user | mandatory }}' \
            -m '0600'
            '/etc/rancher/k3s/k3s.yaml' \
            '/home/{{ user | mandatory }}/.kube/config'

- name: Add ingress-nginx Helm Chart Repository
  kubernetes.core.helm_repository:
    repo_name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Deploy ingress-nginx
  kubernetes.core.helm:
    chart_ref: ingress-nginx/ingress-nginx
    release_name: nginx-ingress
    release_namespace: kube-system
    update_repo_cache: true

- name: Maybe disable k3s-server
  when: not enable_k3s_server
  become: yes
  runit:
    name: k3s-server
    enabled: no
    state: stopped

- name: Maybe enable k3s-server
  when: enable_k3s_server
  become: yes
  runit:
    name: k3s-server
    enabled: yes
    state: restarted            # Restarting in case of version upgrade
