- name: Create personal user
  become: yes
  user:
    name: '{{ user | mandatory }}'
    password: '{{ user_password }}'
    groups:
      - cdrom
      - dialout
      - input
      - kvm
      - optical
      - socklog
      - video
      - wheel
      - xbuilder
    shell: /bin/bash

- name: Add personal user to sudoers
  become: yes
  lineinfile:
    path: /etc/sudoers
    line: '{{ user | mandatory }} ALL=(ALL) NOPASSWD: ALL'
