- name: Install shell packages
  become: yes
  xbps:
    package:
      - bash
      - bash-completion
      - dash
      - oksh
    state: present

- name: Synchronize shell files
  vars:
    dir: shells
  include_role:
    name: lib
    tasks_from: synchronize-files
