- name: Create personal user
  include_tasks: create-user.yaml

- name: Install non-free xbps repository
  xbps:
    package: void-repo-nonfree
    state: present

# TODO This list of packages could probably be broken up some.
- name: Install base system packages
  xbps:
    package:
      - abduco
      - acpid
      - atop
      - base-files
      - bash
      - bc
      - bind-utils
      - blktrace
      - bmake
      - bridge-utils
      - bwm-ng
      - coreutils
      - curl
      - curlftpfs
      - dhcpcd
      - dos2unix
      - dosfstools
      - dstat
      - e2fsprogs
      - ed
      - ethtool
      - eudev
      - extrace
      - f2fs-tools
      - fdupes
      - file
      - fio
      - fuse-sshfs
      - fzy
      - hdparm
      - htop
      - iftop
      - inetutils-telnet
      - ioping
      - iotop
      - iproute2
      - iptables
      - iputils
      - iw
      - iwd
      - jq
      - kbd
      - kmod
      - less
      - libgcc
      - linux
      - logtop
      - lshw
      - lsof
      - ltrace
      - lvm2
      - man-pages
      - mdocml
      - moreutils
      - ncurses
      - nftables
      - openbsd-netcat
      - opendoas
      - openntpd
      - openssh
      - oprofile
      - outils
      - p7zip
      - parallel
      - patch
      - patchutils
      - pciutils
      - perf
      - progress
      - python3
      - python3-pip
      - readline
      - rlwrap
      - rsync
      - socat
      - socklog
      - socklog-void
      - sqlcipher
      - sqlite
      - squashfs-tools
      - stow
      - strace
      - sudo
      - sysfsutils
      - syslinux
      - sysstat
      - tcpflow
      - time
      - traceroute
      - tree
      - unrar
      - unzip
      - usbutils
      - webcat
      - websocat
      - wget
      - wifi-firmware
      - xtools
      - xxd
      - yq
      - zip
    state: present

- name: Enable base system services
  runit:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items:
    - dbus
    - dhcpcd
    - iwd
    - openntpd

- name: Install csv tools
  xbps:
    package:
      - miller
      - xsv
    state: present

- name: Install search tools
  xbps:
    package:
      - ack
      - ripgrep
      - the_silver_searcher
    state: present

- name: Install shells
  include_tasks: install-shells.yaml

- name: Permit non-root users to use ping
  capabilities:
    path: /bin/iputils-ping
    capability: cap_net_raw+ep
