- name: Install boot packages
  become: yes
  xbps:
    package:
      - rsync
      - syslinux
    state: present

- name: Synchronize boot files
  vars:
    dir: boot
  include_role:
    name: lib
    tasks_from: synchronize-files
